### ISSUE TITLE
Interface between the game and python

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/AI-Enhanced-Minecraft#1]
Main features to implement:

- [x] Read the game screen (best if the screen can be minimized).
- [x] Read the key strokes
- [x] Read the Inventory bard.
- [ ] Explore the usage of reading the minimap.

**Comment by zemaria2000** [comment]
Some websites with relevant info:
https://pythonprogramming.net/game-frames-open-cv-python-plays-gta-v/

**Comment by andrefdre** [comment]
When I started working with ros2 I found out that every time you change your code you need to rebuild your workspace which is inconvenient. After googling, I found out that if you run the following `colcon build --symlink-install` you don't need to rerun the build every change.

**Comment by zemaria2000** [comment]
This script (screen_stream) allows us to choose a specific opened window and stream it. It can be used to record / get screenshots from the gameplay

**Comment by zemaria2000** [comment]
One note: recording the screen of a minimized app might actually be quite difficult. According to some sources, the operating system or the app itself, for security reasons, can block such attempts

**Comment by andrefdre** [comment]
While I was testing I noticed that when we run the ROS nodes if the minecraft isn't running, and in case of the inventory if it isn't inside a world it gives an error since there is no information to read. We should solve this problem to make the code more robust.

**Comment by zemaria2000** [comment]
Tried solving this robustness issue. I have 2 solutions in a new branch (improve_robustness). Would then like your opinion on which one is better

**Comment by andrefdre** [comment]
This issue was solved by @zemaria2000 and me with pull requests #7, #8, #11, #10 and #13
